/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Player, Team, GameState, Language } from './types';

// Multi-language dictionary
export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    title: 'PusingBase',
    subtitle: 'Track ining details, 1-10 batting rotations, positions, reserves, and pitch metrics with ease.',
    newGame: 'New Game',
    home: 'Home',
    history: 'Past Games',
    teamSetup: 'Team Setup',
    awayTeam: 'Away Team',
    homeTeam: 'Home Team',
    teamName: 'Team Name',
    presetClassic: 'Classic Players Preset',
    presetAllStar: 'All-Star Presets',
    players: 'Players List',
    name: 'Name',
    number: 'No.',
    position: 'Position',
    startLiveGame: 'Start Scorekeeping',
    liveTracker: 'Live Game Tracker',
    inning: 'Inning',
    top: 'Top of',
    bottom: 'Bottom of',
    outs: 'Outs',
    balls: 'Balls',
    strikes: 'Strikes',
    runs: 'Runs',
    hits: 'Hits',
    errors: 'Errors',
    runsShort: 'R',
    hitsShort: 'H',
    errorsShort: 'E',
    batting: 'Batting',
    pitching: 'Pitching',
    currentBatter: 'Current Batter',
    currentPitcher: 'Current Pitcher',
    count: 'Count',
    bases: 'Bases Occupied',
    single: 'Single (1B)',
    double: 'Double (2B)',
    triple: 'Triple (3B)',
    hr: 'Home Run (HR)',
    strike: 'Strike',
    ball: 'Ball',
    foul: 'Foul',
    strikeout: 'Strikeout (SO)',
    flyout: 'Fly Out',
    groundout: 'Ground Out',
    baseOnBalls: 'Walk (BB)',
    reachError: 'Reach on Error (E)',
    resetCount: 'Reset Count',
    clearBases: 'Clear Bases',
    undo: 'Undo Last Play',
    endGame: 'Trophy / End Game',
    gameSaved: 'Game Saved Successfully!',
    noPastGames: 'No recorded games found. Start a new one above!',
    statusLive: 'In Progress',
    statusFinished: 'Finished',
    winner: 'Winner',
    playEventLogged: 'Play Event Logged',
    playHistory: 'Play-by-Play Event Log',
    p: 'Pitcher (P)',
    c: 'Catcher (C)',
    fb: 'First Base (1B)',
    sb: 'Second Base (2B)',
    tb: 'Third Base (3B)',
    ss: 'Shortstop (SS)',
    lf: 'Left Field (LF)',
    cf: 'Center Field (CF)',
    rf: 'Right Field (RF)',
    sf: 'Rover / Short Fielder (SF)',
    dh: 'Designated Batter (DH)',
    battingOrder: 'Batting Order',
    ab: 'AB',
    h: 'H',
    r: 'R',
    rbi: 'RBI',
    so: 'SO',
    bb: 'BB',
    avg: 'AVG',
    pitches: 'Pitches',
    strikesThrown: 'Str',
    ballsThrown: 'Bal',
    runsAllowed: 'RA',
    gameDate: 'Date Played',
    back: 'Back',
    deleteGame: 'Delete Game',
    confirmDelete: 'Are you sure you want to delete this game?',
    congrats: 'Congratulations to the Winners!',
    finalInningDetail: 'Innings Overview',
  },
  ms: {
    title: 'PusingBase',
    subtitle: 'Jejak perincian ining, susunan pemukul 1-10, posisi padang, pemain simpanan, dan statistik penting.',
    newGame: 'Perlawanan Baru',
    home: 'Utama',
    history: 'Rekod Sukan',
    teamSetup: 'Atur Pasukan',
    awayTeam: 'Pasukan Pelawat (Away)',
    homeTeam: 'Pasukan Tuan Rumah (Home)',
    teamName: 'Nama Pasukan',
    presetClassic: 'Praset Pemain Klasik',
    presetAllStar: 'Praset All-Star',
    players: 'Senarai Pemain',
    name: 'Nama',
    number: 'No.',
    position: 'Posisi',
    startLiveGame: 'Mula Skor Sukan',
    liveTracker: 'Penjejak Sukan Langsung',
    inning: 'Ining',
    top: 'Atas Ining Ke-',
    bottom: 'Bawah Ining Ke-',
    outs: 'Keluar (Out)',
    balls: 'Bola (Ball)',
    strikes: 'Strik (Strike)',
    runs: 'Larian (R)',
    hits: 'Pukulan (H)',
    errors: 'Ralat (E)',
    runsShort: 'L',
    hitsShort: 'P',
    errorsShort: 'R',
    batting: 'Memukul',
    pitching: 'Melontar',
    currentBatter: 'Pemukul Semasa',
    currentPitcher: 'Pelempar Semasa',
    count: 'Kiraan',
    bases: 'Pelari Tapak',
    single: 'Satu Tapak (1B)',
    double: 'Dua Tapak (2B)',
    triple: 'Tiga Tapak (3B)',
    hr: 'Larian Penuh (HR)',
    strike: 'Strik',
    ball: 'Bola',
    foul: 'Bola Foul',
    strikeout: 'Strik-keluar (SO)',
    flyout: 'Mati Sasar (Fly Out)',
    groundout: 'Mati Padang (Ground Out)',
    baseOnBalls: 'Percuma (BB)',
    reachError: 'Ralat Padang (E)',
    resetCount: 'Tetap Semula Kiraan',
    clearBases: 'Kosongkan Tapak',
    undo: 'Batas Play Terakhir',
    endGame: 'Tamat Perlawanan & Simpan',
    gameSaved: 'Perlawanan Berjaya Disimpan!',
    noPastGames: 'Tiada rekod permainan dijumpai. Sila mulakan perlawanan baru!',
    statusLive: 'Sedang Berlangsung',
    statusFinished: 'Tamat',
    winner: 'Pemenang',
    playEventLogged: 'Tindakan Direkod',
    playHistory: 'Log Tindakan Perlawanan',
    p: 'Pelempar (P)',
    c: 'Penangkap (C)',
    fb: 'Tapak Pertama (1B)',
    sb: 'Tapak Kedua (2B)',
    tb: 'Tapak Ketiga (3B)',
    ss: 'Penghalang Pendek (SS)',
    lf: 'Padang Kiri (LF)',
    cf: 'Padang Tengah (CF)',
    rf: 'Padang Kanan (RF)',
    sf: 'Rover Padang (SF)',
    dh: 'Pemukul Khas (DH)',
    battingOrder: 'Turutan Memukul',
    ab: 'AB (Atbat)',
    h: 'P (Hits)',
    r: 'L (Runs)',
    rbi: 'RBI',
    so: 'SO (Out)',
    bb: 'BB (Walk)',
    avg: 'AVG',
    pitches: 'Balingan',
    strikesThrown: 'Str',
    ballsThrown: 'Bol',
    runsAllowed: 'L.Kena',
    gameDate: 'Tarikh Sukan',
    back: 'Kembali',
    deleteGame: 'Padam Rekod',
    confirmDelete: 'Adakah anda pasti mahu memadamkan permainan ini?',
    congrats: 'Tahniah kepada Pasukan Pemenang!',
    finalInningDetail: 'Perincian Markah Ining',
  }
};

// Default Player presets (10 Starters + 5 reserves = 15 total, starting batting order has 10)
export const PRESET_AWAY_PLAYERS: Player[] = [
  { id: 'a1', name: '', number: '', position: 'SS', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'a2', name: '', number: '', position: '2B', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'a3', name: '', number: '', position: 'CF', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'a4', name: '', number: '', position: '3B', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'a5', name: '', number: '', position: '1B', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'a6', name: '', number: '', position: 'LF', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'a7', name: '', number: '', position: 'RF', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'a8', name: '', number: '', position: 'C', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'a9', name: '', number: '', position: 'P', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'a10', name: '', number: '', position: 'SF', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'a11', name: '', number: '', position: 'DH', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'a12', name: '', number: '', position: 'DH', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'a13', name: '', number: '', position: 'DH', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'a14', name: '', number: '', position: 'DH', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'a15', name: '', number: '', position: 'DH', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
];

export const PRESET_HOME_PLAYERS: Player[] = [
  { id: 'h1', name: '', number: '', position: 'CF', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'h2', name: '', number: '', position: 'SS', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'h3', name: '', number: '', position: '1B', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'h4', name: '', number: '', position: 'LF', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'h5', name: '', number: '', position: '3B', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'h6', name: '', number: '', position: '2B', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'h7', name: '', number: '', position: 'RF', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'h8', name: '', number: '', position: 'C', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'h9', name: '', number: '', position: 'P', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'h10', name: '', number: '', position: 'SF', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'h11', name: '', number: '', position: 'DH', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'h12', name: '', number: '', position: 'DH', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'h13', name: '', number: '', position: 'DH', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'h14', name: '', number: '', position: 'DH', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
  { id: 'h15', name: '', number: '', position: 'DH', atBats: 0, runs: 0, hits: 0, rbis: 0, strikeouts: 0, walks: 0, pitchesThrown: 0, strikesThrown: 0, ballsThrown: 0, strikeoutsThrown: 0, walksThrown: 0, runsAllowed: 0 },
];

export function createBlankGame(): GameState {
  return {
    id: 'game_' + Date.now(),
    date: new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    }),
    title: 'Weekend Softball Clash',
    status: 'setup',
    awayTeam: {
      name: 'Pendang Softball Club',
      roster: (() => {
        const r = JSON.parse(JSON.stringify(PRESET_AWAY_PLAYERS));
        if (r[10]) r[10].position = 'EP';
        return r;
      })(),
      battingOrder: PRESET_AWAY_PLAYERS.slice(0, 11).map(p => p.id),
    },
    homeTeam: {
      name: 'Red Stallions FC',
      roster: (() => {
        const r = JSON.parse(JSON.stringify(PRESET_HOME_PLAYERS));
        if (r[10]) r[10].position = 'EP';
        return r;
      })(),
      battingOrder: PRESET_HOME_PLAYERS.slice(0, 11).map(p => p.id),
    },
    currentInning: 1,
    isTopInning: true,
    outs: 0,
    balls: 0,
    strikes: 0,
    runners: {
      first: false,
      second: false,
      third: false,
    },
    inningScores: [
      { inning: 1, awayRuns: null, homeRuns: null },
      { inning: 2, awayRuns: null, homeRuns: null },
      { inning: 3, awayRuns: null, homeRuns: null },
      { inning: 4, awayRuns: null, homeRuns: null },
      { inning: 5, awayRuns: null, homeRuns: null },
      { inning: 6, awayRuns: null, homeRuns: null },
      { inning: 7, awayRuns: null, homeRuns: null },
    ],
    awayRunsTotal: 0,
    homeRunsTotal: 0,
    awayHitsTotal: 0,
    homeHitsTotal: 0,
    awayErrorsTotal: 0,
    homeErrorsTotal: 0,
    currentBatterIndex: {
      away: 0,
      home: 0,
    },
    currentPitcherId: {
      away: 'a9', // Pitcher from Pendang (id of P is a9 in roster setup)
      home: 'h9', // Pitcher from Red Stallions
    },
    gameMode: 'slowpitch',
    logs: [
      {
        id: 'start_log',
        timestamp: new Date().toLocaleTimeString('en-US', { hour12: false, hour: '2-digit', minute: '2-digit' }),
        inning: 1,
        isTop: true,
        messageEn: 'Game setup initialized.',
        messageMs: 'Persediaan perlawanan dimula.',
        score: '0 - 0'
      }
    ],
  };
}

export const SOFTBALL_POSITIONS = [
  { value: 'P', labelEn: 'Pitcher (P)', labelMs: 'Pelempar (P)' },
  { value: 'C', labelEn: 'Catcher (C)', labelMs: 'Penangkap (C)' },
  { value: '1B', labelEn: 'First Base (1B)', labelMs: 'Tapak Pertama (1B)' },
  { value: '2B', labelEn: 'Second Base (2B)', labelMs: 'Tapak Kedua (2B)' },
  { value: '3B', labelEn: 'Third Base (3B)', labelMs: 'Tapak Ketiga (3B)' },
  { value: 'SS', labelEn: 'Shortstop (SS)', labelMs: 'Penghalang Pendek (SS)' },
  { value: 'LF', labelEn: 'Left Field (LF)', labelMs: 'Padang Kiri (LF)' },
  { value: 'CF', labelEn: 'Center Field (CF)', labelMs: 'Padang Tengah (CF)' },
  { value: 'RF', labelEn: 'Right Field (RF)', labelMs: 'Padang Kanan (RF)' },
  { value: 'SF', labelEn: 'Rover / Short Fielder (SF)', labelMs: 'Rover Padang (SF)' },
  { value: 'DH', labelEn: 'Designated Batter (DH)', labelMs: 'Pemukul Khas (DH)' },
  { value: 'DP', labelEn: 'Designated Player (DP)', labelMs: 'Pemain Khas Memukul (DP)' },
  { value: 'EP', labelEn: 'Extra Player (EP - Slowpitch)', labelMs: 'Pemukul Tambahan (EP - Slowpitch)' },
];
